/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WtyczkaRouteImport } from './routes/wtyczka'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as QcRouteImport } from './routes/qc'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorialsIndexRouteImport } from './routes/tutorials.index'
import { Route as SellersIndexRouteImport } from './routes/sellers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TutorialsSlugRouteImport } from './routes/tutorials.$slug'
import { Route as SellersSlugRouteImport } from './routes/sellers.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const WtyczkaRoute = WtyczkaRouteImport.update({
  id: '/wtyczka',
  path: '/wtyczka',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsIndexRoute = TutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersIndexRoute = SellersIndexRouteImport.update({
  id: '/sellers/',
  path: '/sellers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsSlugRoute = TutorialsSlugRouteImport.update({
  id: '/tutorials/$slug',
  path: '/tutorials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersSlugRoute = SellersSlugRouteImport.update({
  id: '/sellers/$slug',
  path: '/sellers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/products': typeof ProductsRoute
  '/qc': typeof QcRoute
  '/tracking': typeof TrackingRoute
  '/wtyczka': typeof WtyczkaRoute
  '/admin/login': typeof AdminLoginRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/sellers/': typeof SellersIndexRoute
  '/tutorials/': typeof TutorialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/products': typeof ProductsRoute
  '/qc': typeof QcRoute
  '/tracking': typeof TrackingRoute
  '/wtyczka': typeof WtyczkaRoute
  '/admin/login': typeof AdminLoginRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/sellers': typeof SellersIndexRoute
  '/tutorials': typeof TutorialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/products': typeof ProductsRoute
  '/qc': typeof QcRoute
  '/tracking': typeof TrackingRoute
  '/wtyczka': typeof WtyczkaRoute
  '/admin/login': typeof AdminLoginRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/sellers/': typeof SellersIndexRoute
  '/tutorials/': typeof TutorialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/products'
    | '/qc'
    | '/tracking'
    | '/wtyczka'
    | '/admin/login'
    | '/sellers/$slug'
    | '/tutorials/$slug'
    | '/admin/'
    | '/sellers/'
    | '/tutorials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/products'
    | '/qc'
    | '/tracking'
    | '/wtyczka'
    | '/admin/login'
    | '/sellers/$slug'
    | '/tutorials/$slug'
    | '/admin'
    | '/sellers'
    | '/tutorials'
  id:
    | '__root__'
    | '/'
    | '/legal'
    | '/products'
    | '/qc'
    | '/tracking'
    | '/wtyczka'
    | '/admin/login'
    | '/sellers/$slug'
    | '/tutorials/$slug'
    | '/admin/'
    | '/sellers/'
    | '/tutorials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRoute
  ProductsRoute: typeof ProductsRoute
  QcRoute: typeof QcRoute
  TrackingRoute: typeof TrackingRoute
  WtyczkaRoute: typeof WtyczkaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  SellersSlugRoute: typeof SellersSlugRoute
  TutorialsSlugRoute: typeof TutorialsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SellersIndexRoute: typeof SellersIndexRoute
  TutorialsIndexRoute: typeof TutorialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wtyczka': {
      id: '/wtyczka'
      path: '/wtyczka'
      fullPath: '/wtyczka'
      preLoaderRoute: typeof WtyczkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/': {
      id: '/tutorials/'
      path: '/tutorials'
      fullPath: '/tutorials/'
      preLoaderRoute: typeof TutorialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/': {
      id: '/sellers/'
      path: '/sellers'
      fullPath: '/sellers/'
      preLoaderRoute: typeof SellersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/$slug': {
      id: '/tutorials/$slug'
      path: '/tutorials/$slug'
      fullPath: '/tutorials/$slug'
      preLoaderRoute: typeof TutorialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/$slug': {
      id: '/sellers/$slug'
      path: '/sellers/$slug'
      fullPath: '/sellers/$slug'
      preLoaderRoute: typeof SellersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRoute,
  ProductsRoute: ProductsRoute,
  QcRoute: QcRoute,
  TrackingRoute: TrackingRoute,
  WtyczkaRoute: WtyczkaRoute,
  AdminLoginRoute: AdminLoginRoute,
  SellersSlugRoute: SellersSlugRoute,
  TutorialsSlugRoute: TutorialsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  SellersIndexRoute: SellersIndexRoute,
  TutorialsIndexRoute: TutorialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
